// Idempotently injects the bestiary page into worker.js as a /bestiary route.
const fs = require('fs');
const path = require('path');
const MOCK = path.resolve(__dirname, '..');
const workerPath = path.join(MOCK, 'worker.js');
const bestiaryPath = path.join(MOCK, 'biomech-bestiary-variants.html');

let worker = fs.readFileSync(workerPath, 'utf8');
const html = fs.readFileSync(bestiaryPath, 'utf8');

// 1) escape for embedding inside a JS template literal
function esc(s) {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

// 2) remove any prior generated block (idempotent)
worker = worker.replace(/\n\/\/ >>> BESTIARY START[\s\S]*?\/\/ >>> BESTIARY END\n/g, '\n');

// 3) add route after the /c route, if missing
if (!worker.includes("'/bestiary'")) {
  worker = worker.replace(
    "if (pathname === '/c') return html(HTML_C);",
    "if (pathname === '/c') return html(HTML_C);\n    if (pathname === '/bestiary') return html(HTML_BESTIARY);"
  );
}

// 4) add an index card before the Proposal C card, if missing
if (!worker.includes('href="/bestiary"')) {
  const card = '  <a href="/bestiary" style="border-color:#1e4030"><div class="tag" style="color:#4f9">BESTIARY · ALL</div><div class="name">BIOMECH VARIANTS</div><div class="desc">Every enemy &middot; silhouette + 4 biomech takes each</div></a>\n';
  worker = worker.replace('  <a href="/c">', card + '  <a href="/c">');
}

// 5) append the generated constant
const block = '\n// >>> BESTIARY START (generated by _recovered/build-worker.cjs — do not edit by hand)\nconst HTML_BESTIARY = `' + esc(html) + '`;\n// >>> BESTIARY END\n';
worker = worker.trimEnd() + '\n' + block;

fs.writeFileSync(workerPath, worker, 'utf8');
console.log('worker.js updated — bestiary bytes:', html.length, '| has route:', worker.includes("'/bestiary'"), '| has card:', worker.includes('href="/bestiary"'));
